# Generated by Django 4.2.27 on 2026-01-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='作品标题')),
                ('category', models.CharField(choices=[('multimodal', 'AI多模态创作'), ('programming', 'AI编程应用'), ('digital_human', 'AI数字人')], max_length=20, verbose_name='分类')),
                ('work_type', models.CharField(choices=[('image', '图片'), ('video', '视频'), ('link', '网页链接')], max_length=10, verbose_name='作品类型')),
                ('student_name', models.CharField(max_length=100, verbose_name='学员姓名')),
                ('description', models.TextField(blank=True, verbose_name='作品描述')),
                ('cover_image', models.ImageField(upload_to='works/covers/', verbose_name='封面图片')),
                ('media_file', models.FileField(blank=True, help_text='图片或视频文件', null=True, upload_to='works/media/', verbose_name='媒体文件')),
                ('content_url', models.URLField(blank=True, help_text='作品链接URL', verbose_name='网页链接')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否发布')),
                ('order', models.IntegerField(default=0, help_text='数字越大越靠前', verbose_name='排序权重')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学员作品',
                'verbose_name_plural': '学员作品',
                'ordering': ['-order', '-created_at'],
            },
        ),
    ]
